project:
  type: website
  output-dir: docs

website:
  title: "Cours"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - L1.qmd

format:
  html:
    theme:
      - cosmo
      - brand
      - customSite.scss
    
    toc: true



